version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8050:80"
    volumes:
      - ./nginx/api_gateway.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/app/static/uploads
    depends_on:
      - web_ui
      - upload
      - image_processing
      - gif_generator

  web_ui:
    build: ./web_ui
    image: web_ui
    restart: unless-stopped
    container_name: web_ui
    volumes:
      - ./uploads:/app/static/uploads
    environment:
      - UPLOAD_SERVICE_URL=http://upload:5002
      - IMAGE_PROCESSING_SERVICE_URL=http://image_processing:5003
      - GIF_GENERATOR_SERVICE_URL=http://gif_generator:5004
      - UPLOADS_ROOT=/app

  upload:
    build: ./file_service
    image: upload
    restart: unless-stopped
    container_name: upload
    volumes:
      - ./uploads:/app/static/uploads
    environment:
      - UPLOADS_ROOT=/app

  image_processing:
    build: ./image_processing
    image: image_processing
    restart: unless-stopped
    container_name: image_processing
    volumes:
      - ./uploads:/app/static/uploads
    environment:
      - UPLOADS_ROOT=/app

  gif_generator:
    build: ./gif_generator
    image: gif_generator
    restart: unless-stopped
    container_name: gif_generator
    volumes:
      - ./uploads:/app/static/uploads
    environment:
      - UPLOADS_ROOT=/app/static/uploads

