services:
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
#    ports:
#      - "6379:6379"
    environment:
      - REDIS_HOST=redis

  web_ui:
    build: ./web_ui
    image: web_ui
    restart: unless-stopped
    container_name: web_ui
    volumes:
      - ./uploads:/app/uploads
      - ./static_files:/app/static
      - ./templates:/app/templates
    environment:
      SESSION_COOKIE_DOMAIN: technobook
    ports:
      - "5000:5000"
