services:
  api:
    image: nginx:latest
    restart: unless-stopped
    container_name: api
    ports:
      - "8050:80"
    volumes:
      - ./nginx/api_gateway.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./uploads:/app/uploads
      - ./static_files:/app/static
      - ./templates:/app/templates

  web_ui:
    build: ./web_ui
    image: web_ui
    restart: unless-stopped
    container_name: web_ui
    volumes:
      - ./uploads:/app/uploads
      - ./static_files:/app/static
      - ./templates:/app/templates
#    environment:
#      SESSION_COOKIE_DOMAIN: localhost
    ports:
      - "5000:5000"

  image_processing:
    build: ./image_processing
    image: image_processing
    restart: unless-stopped
    container_name: image_processing
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "5001:5001"

  gif_generator:
    build: ./gif_generator
    image: gif_generator
    restart: unless-stopped
    container_name: gif_generator
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "5002:5002"
