services:
  api:
    image: nginx
    #container_name: api
    restart: always
    volumes:
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/app/uploads
    ports:
      - "8050:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis
    #container_name: redis
    restart: always
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  webui:
    build: ./srv_webui
    image: webui
    restart: always
    #container_name: webui
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]

  upload:
    build: ./srv_upload
    image: upload
    restart: always
    #container_name: upload
    volumes:
      - ./uploads:/app/uploads
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]

  gifgenerator:
    build: ./srv_gifgenerator
    image: gifgenerator
    restart: always
    #container_name: gifgenerator
    volumes:
      - ./uploads:/app/uploads
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]

