---
- name: Deploy / build server
  hosts: deploy,workers
  roles:
    - role: preconfig
      tags: preconfig
    - role: glusterfs
      tags: glusterfs
#    - role: build
#      tags: build
#    - role: deploy
#      tags: deploy
#    - role: swarm_init
#      tags: swarm_init
#    - role: swarm_leave
#      node_name: server2
#      tags: swarm_leave

- name: Manager
  hosts: managers
  roles:
#    - role: preconfig
#      tags: preconfig

    - role: swarm_init
      tags: swarm_init

- name: Worker
  hosts: workers
  roles:
    - role: swarm_join
      type: worker
      tags: swarm_join

#    - role: swarm_leave
#      tags: swarm_leave



