---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      tags: deploy
      test: "Тестовая переменная для проверки"
#    - role: swarm_init
#      tags: swarm_init

- name: Manager
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
#    - role: swarm_join
#      tags: swarm_join

- name: Worker
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
#    - role: swarm_join
#      tags: swarm_join
