---
- name: На всех серверах
  hosts: all
  roles:
    - role: preconfig
      tags: preconfig
    - role: glusterfs
      tags: glusterfs
    - role: swarm_init
      tags: swarm_init

- name: Сборка и выкладка
  hosts: deploy
  roles:
    - role: docker_registry
      tags: registry
    - role: build
      tags: build
    - role: deploy
      tags: deploy



