---
- name: Печатаем токены
  debug:
    msg: "token_manager {{ token.swarm_facts.JoinTokens.Manager }}"
- name: print
  debug:
    msg: "token_worker {{ token.swarm_facts.JoinTokens.Worker }}"

- name: Подключение
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ advertise_addr }}"
    join_token: "{{ hostvars['redc1.gradient.ru']['token_worker'] }}"
