---
# Глобальные переменные для всех узлов
brick_dir: "/GlusterData/brick1"
mount_point: "/mnt/gvolume"
volume_name: "gvolume"
gluster_packages:
  - glusterfs-server
  - glusterfs-fuse
  - glusterfs-libs
  - glusterfs
  - glusterfs-cli
  - glusterfs-client-xlators
  - libgfapi0
glusterconfigs:
  - "/var/lib/glusterd"
  - "/etc/glusterfs"

advertise_addr: 10.90.13.171
node_name: "{{ groups['workers'] }}"

registry_name: "/redc1:4000/"
network_name: "gifmaker"
docker_host: "unix:///var/run/docker.sock"  # Укажите правильный путь к вашему Docker daemon

services:
  - name: upload
    version: "latest"
  - name: webui
    version: "latest"
  - name: gifgenerator
    version: "latest"
  - api
  - redis

non_build_services:
  - api
  - redis
