---
# Глобальные переменные для всех узлов
brick_dir: "/GlusterData/brick1"
mount_point: "/mnt/gvolume"
volume_name: "gvolume"
gluster_packages:
  - glusterfs-server
  - glusterfs-fuse
  - glusterfs-libs
  - glusterfs
  - glusterfs-cli
  - glusterfs-client-xlators
  - libgfapi0
glusterconfigs:
  - "/var/lib/glusterd"
  - "/etc/glusterfs"

advertise_addr: 10.90.13.4
node_name: "{{ groups['workers'] }}"

registry_name: "/redc1:4000/"
network_name: "gifmaker"

services:
  - name: srv_upload
    version: "latest"
  - name: srv_webui
    version: "latest"
  - name: srv_gifgenerator
    version: "latest"
  - srv_api
  - redis

non_build_services:
  - srv_api
  - redis
