---
- name: Создание тома GlusterFS
  gluster.gluster.gluster_volume:
    name: "{{ volume_name }}"  # Имя тома
    state: present             # Создание тома
    replicas: 3                # Репликация на 3 узла
    bricks: "{{ brick_dir }}"  # Директория для хранения данных
    cluster: "{{ groups['all'] }}"  # Узлы кластера из группы hosts
    force: true                # Принудительное создание тома
  run_once: true               # Задача выполняется только один раз

- name: Монтирование тома на всех узлах
  mount:
    path: "{{ mount_point }}"  # Точка монтирования
    src: "{{ inventory_hostname }}:{{ volume_name }}"  # Источник монтирования (GlusterFS-том)
    fstype: glusterfs          # Тип файловой системы
    state: mounted             # Монтирование тома
  delegate_to: "{{ item }}"    # Делегирование задачи на каждый узел
  loop: "{{ groups['all'] }}"  # Цикл по всем узлам из группы hosts
