---
- name: Create GlusterFS volume
  command: >
    gluster volume create {{ glusterfs_volume_name }} replica 3 {{ groups['workers'] | join(':/') }}{{ glusterfs_bricks[0] }}
  register: volume_create_result
  changed_when: "'Volume creation successful' in volume_create_result.stdout"
  tags: create

- name: Start GlusterFS volume
  command: gluster volume start {{ glusterfs_volume_name }}
  when: "'Volume creation successful' in volume_create_result.stdout"
  tags: create

- name: Mount GlusterFS volume
  mount:
    path: "{{ glusterfs_mount_point }}"
    src: "{{ item }}"
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted
  with_items:
    - "{{ groups['managers'][0] }}:{{ glusterfs_volume_name }}"
  tags: create
