---
- name: Install GlusterFS packages
  package:
    name: glusterfs-server
    state: present
  tags: install

- name: Start and enable glusterd service
  systemd:
    name: glusterd
    state: started
    enabled: yes
  tags: install
