---
- name: Инициализация swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token
  when: inventory_hostname == groups['managers'][0]

- name: Сохранение токенов
  set_fact:
    token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"
    cacheable: yes
  when: inventory_hostname == groups['managers'][0]

- name: Печать токена менеджера
  debug:
    msg: "token_manager: {{ token_manager }}"
  when: inventory_hostname == groups['managers'][0]

- name: Печать токена worker
  debug:
    msg: "token_worker: {{ hostvars[groups['managers'][0]]['token_worker'] }}"
  when: inventory_hostname in groups['workers']

- name: Подключение worker к swarm
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ advertise_addr }}"
    join_token: "{{ hostvars[groups['managers'][0]]['token_worker'] }}"
  when: inventory_hostname in groups['workers']
