---
- name: Установка дополнительных пакетов
  dnf:
    name:
      - curl
      - python3-pip
      - docker-ce
      - docker-compose
    state: present

- name: Проверка что Docker установлен и перезагружен
  service:
    name: docker
    state: restarted
    enabled: true

- name: Установка pip пакетов
  pip:
    name: docker
    state: present


